### PR TITLE
make this a pkg

### PR DESCRIPTION
**Pull request by maelle**
cf #3

### CODE REVIEW

**Comment by maelle** [comment]
Please try installing the package and running the app and confirms it work :-)

**Comment by maelle** [comment]
(it works for me :wink:)

**Comment by maelle** [comment]
When this is merged please rename the repo to "rweekly.highlights".

**Comment by haozhu233** [comment]
@maelle I just made some changes to this package. I moved the app from inst to R so it looks more natural. Also, I added a "copy to clipboard" button to the app. :D

**Comment by maelle** [comment]
Cool!

What is the official guidance on app code location? I thought it was inst. But anyway this is not going om CRAN 😁

**Comment by qinwf** [comment]
LGTM

**Comment by haozhu233** [comment]
@maelle Haha, I don't think there is any official guidance~ I think it's a better idea to put it in the R folder because in this way you can import function in the regular r packaging way. If you want, you can even write tests against parts of your app.

**Pull request merged**
